// AUTOGENERATED FILE; see /tmp/gopath/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "f39987a"
	VERSION   string = "1.8.0-dev"
	BUILDTIME string = "Thu Aug 27 02:05:12 UTC 2015"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
